# QA：以 iPhone 尺寸跑完整使用流程並截圖（示範模式）
import sys, http.server, threading, functools, os
from playwright.sync_api import sync_playwright, expect
ROOT = os.path.join(os.path.dirname(__file__), '..', 'web')
SHOTS = sys.argv[1] if len(sys.argv) > 1 else '/tmp/shots'
os.makedirs(SHOTS, exist_ok=True)
srv = http.server.ThreadingHTTPServer(('127.0.0.1', 8765), functools.partial(http.server.SimpleHTTPRequestHandler, directory=ROOT))
threading.Thread(target=srv.serve_forever, daemon=True).start()
errors = []
with sync_playwright() as p:
    b = p.chromium.launch()
    ctx = b.new_context(viewport={'width': 390, 'height': 844}, device_scale_factor=2, is_mobile=True, has_touch=True, locale='zh-TW', accept_downloads=True)
    ctx.route('**/*', lambda r: r.abort() if not r.request.url.startswith('http://127.0.0.1') else r.continue_())
    pg = ctx.new_page()
    pg.on('pageerror', lambda e: errors.append(str(e)))
    pg.on('console', lambda m: m.type == 'error' and 'net::' not in m.text and 'Failed to load resource' not in m.text and errors.append(m.text))
    shot = lambda n: pg.screenshot(path=f'{SHOTS}/{n}.png')
    pg.goto('http://127.0.0.1:8765/index.html')
    expect(pg.get_by_text('東京五日遊')).to_be_visible(); shot('01-home')
    pg.get_by_text('東京五日遊').click()
    expect(pg.get_by_role('dialog', name='你是哪一位？')).to_be_visible(); shot('02-identity')
    pg.get_by_role('dialog').get_by_text('小安', exact=True).click()
    expect(pg.get_by_text('你是 小安')).to_be_visible(); pg.wait_for_timeout(300); shot('03-ledger-list')
    # 新增支出
    pg.get_by_role('button', name='記一筆').click()
    dlg = pg.get_by_role('dialog')
    dlg.get_by_label('金額').fill('1200')
    dlg.get_by_placeholder('項目名稱，例如：晚餐').fill('居酒屋')
    pg.wait_for_timeout(300); shot('04-editor')
    dlg.get_by_role('button', name='記下這筆').click()
    expect(pg.get_by_text('居酒屋')).to_be_visible()
    # 外幣 + 自訂金額
    pg.get_by_role('button', name='記一筆').click()
    dlg = pg.get_by_role('dialog')
    dlg.get_by_label('幣別').select_option('JPY')
    dlg.get_by_label('金額').fill('3000')
    dlg.get_by_placeholder('項目名稱，例如：晚餐').fill('便利商店')
    dlg.get_by_role('button', name='自訂金額').click()
    dlg.get_by_label('小安 金額').fill('2000'); dlg.get_by_label('阿哲 金額').fill('1000')
    dlg.get_by_label('米米 參與分攤').uncheck(); dlg.get_by_label('Kai 參與分攤').uncheck()
    expect(dlg.get_by_text('金額剛好分配完畢')).to_be_visible()
    expect(dlg.get_by_label('匯率')).to_have_value('0.213')
    shot('05-editor-foreign')
    dlg.get_by_role('button', name='記下這筆').click()
    expect(pg.get_by_text('便利商店')).to_be_visible()
    # 修改並刪除
    pg.get_by_text('居酒屋').click()
    pg.get_by_role('dialog').get_by_label('金額').fill('1500')
    pg.get_by_role('button', name='儲存修改').click()
    expect(pg.get_by_text('NT$1,500').first).to_be_visible()
    pg.get_by_text('居酒屋').click()
    pg.get_by_role('button', name='刪除這筆').click()
    pg.get_by_role('button', name='刪除', exact=True).click()
    expect(pg.get_by_text('居酒屋')).to_have_count(0)
    # 結算
    pg.get_by_role('tab', name='結算').click(); pg.wait_for_timeout(200); shot('06-settle')
    n_before = pg.locator('.xfer').count()
    pg.locator('.xfer').first.get_by_role('button', name='記為已付款').click()
    pg.get_by_role('dialog').get_by_role('button', name='記為已付款').click()
    pg.wait_for_timeout(400)
    assert pg.locator('.xfer').count() == n_before - 1, 'settled transfer should disappear'
    # 統計＋匯出
    pg.get_by_role('tab', name='統計').click(); pg.wait_for_timeout(200); shot('07-stats')
    with pg.expect_download() as d: pg.get_by_role('button', name='匯出明細').click()
    csv = open(d.value.path(), encoding='utf-8-sig').read()
    assert '便利商店' in csv and '日期' in csv, csv[:200]
    with pg.expect_download() as d: pg.get_by_role('button', name='匯出統計').click()
    # 成員
    pg.get_by_role('tab', name='成員').click(); pg.wait_for_timeout(200); shot('08-members')
    pg.get_by_placeholder('新成員名字').fill('Leo'); pg.get_by_role('button', name='新增').click()
    expect(pg.locator('.member', has_text='Leo')).to_have_count(1)
    pg.locator('.member', has_text='小安').click()
    dlg = pg.get_by_role('dialog')
    dlg.get_by_placeholder('國泰世華').fill('台新'); dlg.get_by_placeholder('帳號', exact=True).fill('2888-1234')
    shot('09-member-edit')
    dlg.get_by_role('button', name='儲存').click(); pg.wait_for_timeout(300)
    pg.locator('.member', has_text='阿哲').click()
    expect(pg.get_by_role('dialog').get_by_text('只有 阿哲 本人可以修改匯款資訊。')).to_be_visible()
    pg.keyboard.press('Escape'); pg.wait_for_timeout(300)
    pg.locator('.member', has_text='Leo').click()
    pg.get_by_role('button', name='移除成員').click(); pg.get_by_role('button', name='移除', exact=True).click()
    expect(pg.locator('.member', has_text='Leo')).to_have_count(0)
    # 設定改名
    pg.get_by_role('button', name='帳本設定').click()
    pg.get_by_role('dialog').locator('input.input').first.fill('東京五日遊 2026')
    pg.get_by_role('dialog').get_by_role('button', name='儲存').click()
    expect(pg.locator('.top-title')).to_have_text('東京五日遊 2026')
    # 建立新帳本（USD）
    pg.get_by_role('button', name='回帳本列表').click()
    pg.get_by_role('button', name='建立帳本').click()
    dlg = pg.get_by_role('dialog')
    dlg.get_by_placeholder('例如：東京五日遊').fill('紐約出差'); dlg.get_by_label('幣別').select_option('USD')
    dlg.get_by_placeholder('輸入名字後按「加入」').fill('Amy'); dlg.get_by_role('button', name='加入', exact=True).click()
    shot('10-create')
    dlg.get_by_role('button', name='建立帳本').click()
    expect(pg.locator('.top-title')).to_have_text('紐約出差')
    expect(pg.get_by_text('你是 我（示範）')).to_be_visible(); shot('11-new-ledger')
    # 深色模式
    pg.emulate_media(color_scheme='dark'); pg.get_by_role('button', name='回帳本列表').click(); pg.get_by_text('東京五日遊 2026').click(); pg.wait_for_timeout(300); shot('12-dark')
    b.close()
srv.shutdown()
print('E2E OK' if not errors else 'CONSOLE ERRORS:\n' + '\n'.join(errors))
sys.exit(1 if errors else 0)
