# QA：以 iPhone 尺寸跑完整使用流程並截圖（示範模式）
import sys, http.server, threading, functools, os
from playwright.sync_api import sync_playwright, expect
ROOT = os.path.join(os.path.dirname(__file__), '..', 'web')
SHOTS = sys.argv[1] if len(sys.argv) > 1 else '/tmp/shots'
os.makedirs(SHOTS, exist_ok=True)
srv = http.server.ThreadingHTTPServer(('127.0.0.1', 8765), functools.partial(http.server.SimpleHTTPRequestHandler, directory=ROOT))
threading.Thread(target=srv.serve_forever, daemon=True).start()
errors = []
with sync_playwright() as p:
    b = p.chromium.launch()
    ctx = b.new_context(viewport={'width': 390, 'height': 844}, device_scale_factor=2, is_mobile=True, has_touch=True, locale='zh-TW', accept_downloads=True)
    ctx.route('**/*', lambda r: r.abort() if not r.request.url.startswith('http://127.0.0.1') else r.continue_())
    pg = ctx.new_page()
    pg.on('pageerror', lambda e: errors.append(str(e)))
    pg.on('console', lambda m: m.type == 'error' and 'net::' not in m.text and 'Failed to load resource' not in m.text and errors.append(m.text))
    shot = lambda n: pg.screenshot(path=f'{SHOTS}/{n}.png')
    pg.goto('http://127.0.0.1:8765/index.html')
    expect(pg.get_by_text('東京五日遊')).to_be_visible(); shot('01-home')
    pg.get_by_text('東京五日遊').click()
    expect(pg.get_by_role('dialog', name='歡迎加入「東京五日遊」')).to_be_visible()
    expect(pg.get_by_role('dialog').get_by_role('button', name='關閉')).to_have_count(0)
    pg.keyboard.press('Escape'); pg.wait_for_timeout(300)
    expect(pg.get_by_role('dialog')).to_be_visible()  # 必須先選身分
    shot('02-identity')
    pg.get_by_role('dialog').get_by_text('小安', exact=True).click()
    expect(pg.get_by_text('你是 小安')).to_be_visible(); pg.wait_for_timeout(300); shot('03-ledger-list')
    # B1：回首頁看到我的餘額
    pg.get_by_role('button', name='回帳本列表').click()
    expect(pg.locator('.ledger-card .lc-bal')).to_contain_text('應付'); shot('01b-home-balance')
    pg.get_by_text('東京五日遊').click(); expect(pg.get_by_text('你是 小安')).to_be_visible()
    # 新增支出
    pg.get_by_role('button', name='使用說明').click()
    expect(pg.get_by_role('dialog', name='使用說明').get_by_text('在 LINE 直接打字記帳')).to_be_visible()
    pg.get_by_role('dialog').get_by_text('記一筆', exact=True).click()
    expect(pg.get_by_role('dialog').get_by_text('所有人平均', exact=False).first).to_be_visible()
    shot('17-help')
    pg.keyboard.press('Escape'); pg.wait_for_timeout(300)
    pg.get_by_role('button', name='記一筆').click()
    dlg = pg.get_by_role('dialog')
    dlg.get_by_label('金額').fill('1200')
    expect(dlg.locator('.form.editor')).not_to_contain_text('null')
    last = dlg.get_by_role('button', name='📦 其他')
    box = last.bounding_box(); assert box and box['x'] + box['width'] <= 390, '分類要多排顯示，不需橫移'
    dlg.get_by_placeholder('項目名稱，例如：晚餐').fill('居酒屋')
    pg.wait_for_timeout(300); shot('04-editor')
    dlg.get_by_role('button', name='記下這筆').click()
    expect(pg.get_by_text('居酒屋')).to_be_visible()
    # 外幣 + 自訂金額
    pg.get_by_role('button', name='記一筆').click()
    dlg = pg.get_by_role('dialog')
    dlg.get_by_label('幣別').select_option('JPY')
    dlg.get_by_label('金額').fill('3000')
    dlg.get_by_placeholder('項目名稱，例如：晚餐').fill('便利商店')
    dlg.get_by_role('button', name='自訂金額').click()
    dlg.get_by_label('小安 金額').fill('2000'); dlg.get_by_label('阿哲 金額').fill('1000')
    expect(dlg.get_by_label('米米 參與分攤')).to_be_checked()  # 自訂金額預設全員勾選
    dlg.get_by_label('阿哲 金額').fill('')
    expect(dlg.get_by_role('button', name='所有人平均')).to_have_attribute('aria-pressed', 'true')  # 預設：所有人平均
    expect(dlg.get_by_text('不足 ¥1,000 由勾選的 4 人平均分攤', exact=False)).to_be_visible()
    shot('05b-fill-all')
    dlg.get_by_role('button', name='沒填的人平均').click()
    expect(dlg.get_by_text('剩下 ¥1,000 由 3 位沒填金額的人平分', exact=False)).to_be_visible()  # 小安填 2000，其餘 3 人平分剩下
    shot('05a-amount-remainder')
    dlg.get_by_label('阿哲 金額').fill('1000')
    dlg.get_by_label('米米 參與分攤').uncheck(); dlg.get_by_label('Kai 參與分攤').uncheck()
    expect(dlg.get_by_text('金額剛好分配完畢')).to_be_visible()
    expect(dlg.locator('.rate-src')).to_contain_text('當日匯率')
    r1 = dlg.get_by_label('匯率').input_value()
    expect(dlg.locator('details.more')).not_to_have_attribute('open', '')  # A3：更多選項預設收合
    expect(dlg.locator('details.more summary')).to_contain_text('今天')
    dlg.get_by_text('更多選項').click()
    dlg.locator('input[type=date]').fill('2026-12-06'); dlg.locator('input[type=date]').dispatch_event('change')
    pg.wait_for_timeout(300)
    assert dlg.get_by_label('匯率').input_value() != r1, '換日期要換匯率'
    expect(dlg.locator('.rate-src')).to_contain_text('2026-12-06 當日匯率')
    dlg.get_by_label('匯率').fill('0.2')
    expect(dlg.locator('.rate-src')).to_contain_text('手動輸入')
    shot('05-editor-foreign')
    dlg.get_by_role('button', name='記下這筆').click()
    expect(pg.get_by_text('便利商店')).to_be_visible()
    # 自訂金額：沒填的人平分剩下的
    pg.get_by_role('button', name='記一筆').click()
    dlg = pg.get_by_role('dialog')
    dlg.get_by_label('幣別').select_option('TWD')
    dlg.get_by_label('金額').fill('1000'); dlg.get_by_placeholder('項目名稱，例如：晚餐').fill('烤肉')
    dlg.get_by_role('button', name='自訂金額').click()
    dlg.get_by_label('小安 金額').fill('400')
    expect(dlg.locator('.split-sum')).to_contain_text('不足 NT$600 由勾選的 4 人平均分攤')
    expect(dlg.locator('.split-pv[data-id=m0]')).to_have_text('NT$550')  # 400 + 150
    dlg.get_by_role('button', name='沒填的人平均').click()
    expect(dlg.locator('.split-sum')).to_contain_text('剩下 NT$600 由 3 位')
    expect(dlg.locator('.split-pv[data-id=m1]')).to_have_text('NT$200')
    expect(dlg.get_by_label('阿哲 金額')).to_have_attribute('placeholder', '平分')
    shot('16-amount-remainder')
    dlg.get_by_label('阿哲 金額').fill('700')
    expect(dlg.locator('.split-sum')).to_contain_text('超出')
    dlg.get_by_label('阿哲 金額').fill('')
    dlg.get_by_role('button', name='記下這筆').click()
    expect(pg.get_by_text('烤肉')).to_be_visible()
    # 修改並刪除
    pg.get_by_text('居酒屋').click()
    pg.get_by_role('dialog').get_by_label('金額').fill('1500')
    pg.get_by_role('button', name='儲存修改').click()
    expect(pg.get_by_text('NT$1,500').first).to_be_visible()
    pg.get_by_text('居酒屋').click()
    pg.get_by_role('button', name='刪除這筆').click()
    pg.get_by_role('button', name='刪除', exact=True).click()
    expect(pg.locator('.rec', has_text='居酒屋')).to_have_count(0)
    # A4：刪除後可復原
    expect(pg.locator('.toast .toast-act')).to_have_text('復原'); shot('18-undo')
    pg.locator('.toast .toast-act').click()
    expect(pg.locator('.rec', has_text='居酒屋')).to_be_visible()
    expect(pg.locator('.rec.flash')).to_have_count(1)  # C3：復原的那筆會亮一下
    pg.locator('.rec', has_text='居酒屋').click()
    pg.get_by_role('button', name='刪除這筆').click()
    pg.get_by_role('button', name='刪除', exact=True).click()
    expect(pg.locator('.rec', has_text='居酒屋')).to_have_count(0)
    pg.wait_for_timeout(5200)
    # B4：明細篩選
    pg.get_by_role('group', name='篩選').get_by_role('button', name='我付的').click()
    for t in pg.locator('.rec-main small').all_inner_texts(): assert t.startswith('小安'), t
    pg.get_by_role('group', name='篩選').get_by_role('button', name='🎟️ 門票活動').click()
    expect(pg.locator('.rec')).to_have_count(1)
    shot('19-filters')
    pg.get_by_role('group', name='篩選').get_by_role('button', name='全部').click()
    # 結算
    pg.get_by_role('tab', name='結算').click(); pg.wait_for_timeout(200)
    pg.get_by_label('顯示幣別').select_option('JPY'); pg.wait_for_timeout(300)
    expect(pg.locator('.xfer-mid strong').first).to_contain_text('¥')
    expect(pg.get_by_text('僅供參考', exact=False)).to_be_visible()
    shot('06-settle')
    pg.get_by_label('顯示幣別').select_option('TWD'); pg.wait_for_timeout(200)
    expect(pg.locator('.tab-body h3.sec-title').first).to_contain_text('我要付的')  # B2：跟我有關的在最上面
    n_before = pg.locator('.xfer').count()
    pg.locator('.xfer').first.get_by_role('button', name='記為已付款').click()
    pg.get_by_role('dialog').get_by_role('button', name='記為已付款').click()
    pg.wait_for_timeout(400)
    assert pg.locator('.xfer').count() == n_before - 1, 'settled transfer should disappear'
    # 統計＋匯出
    pg.get_by_role('tab', name='統計').click(); pg.wait_for_timeout(200); shot('07-stats')
    expect(pg.get_by_text('每日平均')).to_be_visible(); expect(pg.locator('svg.trend rect')).not_to_have_count(0)
    expect(pg.get_by_text('前 5 大支出')).to_be_visible(); expect(pg.locator('table.cross')).to_be_visible()
    pg.locator('.top5').scroll_into_view_if_needed(); shot('07b-stats-more')
    pg.locator('table.cross').scroll_into_view_if_needed(); shot('07c-stats-cross')
    pg.get_by_role('button', name='我的').click(); expect(pg.get_by_text('我分攤的支出')).to_be_visible(); expect(pg.get_by_text('占團體')).to_be_visible()
    pg.get_by_role('button', name='全體').click()
    # B5：點分類跳到明細並套用篩選
    pg.get_by_role('button', name='看 住宿 的明細').click()
    expect(pg.get_by_role('tab', name='明細')).to_have_attribute('aria-selected', 'true')
    expect(pg.locator('.rec')).to_have_count(1)
    pg.get_by_role('group', name='篩選').get_by_role('button', name='全部').click()
    pg.get_by_role('tab', name='統計').click(); pg.wait_for_timeout(200)
    ctx.grant_permissions(['clipboard-read', 'clipboard-write'])
    pg.get_by_role('button', name='複製表格').click()
    assert '\t' in pg.evaluate('navigator.clipboard.readText()'), 'TSV'
    with pg.expect_download() as d: pg.get_by_role('button', name='匯出明細').click()
    csv = open(d.value.path(), encoding='utf-8-sig').read()
    assert '便利商店' in csv and '日期' in csv, csv[:200]
    with pg.expect_download() as d: pg.get_by_role('button', name='匯出統計').click()
    # 成員
    pg.get_by_role('tab', name='成員').click(); pg.wait_for_timeout(200); shot('08-members')
    pg.get_by_placeholder('新成員名字').fill('Leo'); pg.get_by_role('button', name='新增').click()
    expect(pg.locator('.member', has_text='Leo')).to_have_count(1)
    pg.locator('.member', has_text='小安').click()
    dlg = pg.get_by_role('dialog')
    dlg.get_by_placeholder('國泰世華').fill('台新'); dlg.get_by_placeholder('帳號', exact=True).fill('2888-1234')
    shot('09-member-edit')
    dlg.get_by_role('button', name='儲存').click(); pg.wait_for_timeout(300)
    pg.locator('.member', has_text='阿哲').click()
    expect(pg.get_by_role('dialog').get_by_text('只有 阿哲 本人可以修改匯款資訊。')).to_be_visible()
    pg.keyboard.press('Escape'); pg.wait_for_timeout(300)
    pg.locator('.member', has_text='Leo').click()
    pg.get_by_role('button', name='移除成員').click(); pg.get_by_role('button', name='移除', exact=True).click()
    expect(pg.locator('.member', has_text='Leo')).to_have_count(0)
    # 設定改名
    pg.get_by_role('button', name='帳本設定').click()
    pg.get_by_role('dialog').locator('input.input').first.fill('東京五日遊 2026')
    pg.get_by_label('選擇要固定的幣別').select_option('JPY'); pg.get_by_role('button', name='加入固定匯率').click()
    pg.get_by_label('JPY 固定匯率', exact=True).fill('0.205'); shot('13-settings')
    pg.get_by_role('dialog').get_by_role('button', name='儲存').click()
    expect(pg.locator('.top-title')).to_have_text('東京五日遊 2026')
    pg.get_by_role('tab', name='明細').click()
    pg.get_by_role('button', name='記一筆').click(); d2 = pg.get_by_role('dialog')
    d2.get_by_label('幣別').select_option('JPY')
    expect(d2.get_by_label('匯率')).to_have_value('0.205'); expect(d2.locator('.rate-src')).to_contain_text('固定匯率')
    expect(d2.get_by_role('button', name='🧋 飲料')).to_be_visible(); expect(d2.get_by_role('button', name='🥐 早午餐')).to_be_visible()
    pg.keyboard.press('Escape'); pg.wait_for_timeout(300)
    # 建立新帳本（USD）
    pg.get_by_role('button', name='回帳本列表').click()
    pg.get_by_role('button', name='建立帳本').click()
    dlg = pg.get_by_role('dialog')
    dlg.get_by_placeholder('例如：東京五日遊').fill('紐約出差'); dlg.get_by_label('幣別').select_option('USD')
    dlg.get_by_placeholder('輸入名字後按「加入」').fill('Amy'); dlg.get_by_role('button', name='加入', exact=True).click()
    shot('10-create')
    dlg.get_by_role('button', name='建立帳本').click()
    expect(pg.locator('.top-title')).to_have_text('紐約出差')
    expect(pg.get_by_text('你是 我（示範）')).to_be_visible(); shot('11-new-ledger')
    # 個人匯款資訊記憶：我的帳號填一次 → 所有帳本同步
    pg.get_by_role('button', name='回帳本列表').click()
    pg.get_by_role('button', name='我的帳號').click()
    d3 = pg.get_by_role('dialog'); d3.get_by_label('帳號', exact=True).fill('9999-8888'); d3.get_by_label('國泰世華').fill('永豐')
    shot('14-account-pay')
    d3.get_by_role('button', name='儲存匯款資訊').click(); pg.wait_for_timeout(400)
    pg.get_by_text('紐約出差').click(); pg.get_by_role('tab', name='成員').click()
    pg.locator('.member', has_text='我（示範）').click()
    expect(pg.get_by_role('dialog').get_by_label('帳號', exact=True)).to_have_value('9999-8888')
    expect(pg.get_by_role('dialog').get_by_text('同步到我所有的帳本')).to_be_visible()
    shot('15-member-sync')
    pg.keyboard.press('Escape'); pg.wait_for_timeout(300)
    pg.get_by_role('button', name='回帳本列表').click(); pg.get_by_text('東京五日遊 2026').click(); pg.get_by_role('tab', name='成員').click()
    pg.locator('.member', has_text='小安').click()
    expect(pg.get_by_role('dialog').get_by_label('帳號', exact=True)).to_have_value('9999-8888')
    pg.keyboard.press('Escape'); pg.wait_for_timeout(300)
    pg.get_by_role('button', name='回帳本列表').click()
    # 深色模式
    pg.emulate_media(color_scheme='dark'); pg.get_by_text('東京五日遊 2026').click(); pg.wait_for_timeout(300); shot('12-dark')
    b.close()
srv.shutdown()
print('E2E OK' if not errors else 'CONSOLE ERRORS:\n' + '\n'.join(errors))
sys.exit(1 if errors else 0)
